package osbot_scripts.sections.total.progress;

public enum MainState {

	
	CREATE_CHARACTER_DESIGN,
	TALK_TO_GIELINOR_GUIDE_ONE,
	SURVIVAL_EXPERT,
	COOKING_GUIDE_SECTION,
	QUEST_SECTION,
	MINING_SECTION,
	COMBAT_SECTION,
	BANKING_AREA_SECTION,
	CHURCH_GUIDE_SECTION,
	WIZARD_GUIDE_SECTION,
	IN_LUMBRIDGE,
}
