package osbot_scripts.sections.progress;

public enum BankGuideSectionProgress {

	WALK_TO_BANKING_AREA,
	OPEN_BANK,
	TALK_TO_BANKER,
	VOTES,
	OPEN_DOOR,
	TALK_TO_ADVISOR,
	CLICK_ACCOUNT_MANAGER,
	TALK_TO_ADVISOR_ABOUT_AM,
	CLICK_DOOR_OUTSIDE,
	OPEN_CHURCH_DOOR,
	
}
