package osbot_scripts.sections.progress;

public enum CharacterCreationSectionProgress {

	CREATING_RANDOM_CHARACTER,
	CHOOSING_HEAD,
	CHOOSING_JAW,
	CHOOSING_TORSO,
	CHOOSING_ARMS,
	CHOOSING_HANDS,
	CHOOSING_LEGS,
	CHOOSING_FEET,
	ACCEPT_CHARACTER,
	TALK_WITH_NPC_1,
}
