package osbot_scripts.sections.progress;

public enum CombatGuideSectionProgress {

	TALK_WITH_INSTRUCTOR,
	OPEN_EQUIPMENT_TAB,
	OPEN_EQUIPMENT_STATS,
	EQUIP_DAGGER,
	TALK_INSTRUCTOR_ABOUT_DAGGER,
	EQUIP_SWORD_AND_SHIELD,
	OPEN_COMBAT_TAB,
	WALK_TO_GATE_WITH_MOUSE,
	ATTACK_WITH_RAT_SWORD,
	CLICK_GATE_BACK_TO_INSTRUCTOR,
	ATTACK_RAT,
	GO_UP_LADDER,
	
	
	
}
