package osbot_scripts.sections.progress;

public enum MiningGuildeSectionProgress {

	WALK_TO_INSTRUCTOR,
	TALK_WITH_INSTRUCTOR,
	PROSPECTING_TIN,
	PROSPECTING_COPPER,
	TALK_WITH_INSTRUCTOR_ABOUT_TIN_AND_COPPER,
	MINING_TIN,
	MINING_COPPER,
	SMELTING,
	TALK_WITH_INSTRUCTOR_ABOUT_SMELTING,
	SMITHING_A_DAGGER,
	CHOOSING_DAGGER_IN_INTERFACE,
	WALKING_TO_GATE
}
